#include "PluginProcessor.h"
#include "PluginEditor.h"

static const juce::String BASE_URL = "https://garebear99.github.io/Instrudio/Instrudio_v2/";

InstrudioProcessor::InstrudioProcessor()
    : AudioProcessor(BusesProperties()
        .withOutput("Output", juce::AudioChannelSet::stereo(), true))
{
}

InstrudioProcessor::~InstrudioProcessor() {}

void InstrudioProcessor::prepareToPlay(double, int) {}
void InstrudioProcessor::releaseResources() {}

void InstrudioProcessor::processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midiMessages)
{
    buffer.clear();

    // Forward incoming DAW MIDI to the webview via the editor
    // (The editor polls for MIDI in its timer callback)

    // Merge any MIDI generated by the webview (user playing the HTML instrument)
    // into the output MIDI buffer so the DAW receives it
    {
        const juce::ScopedLock sl(midiLock);
        if (!pendingWebMidi.isEmpty())
        {
            midiMessages.addEvents(pendingWebMidi, 0, buffer.getNumSamples(), 0);
            pendingWebMidi.clear();
        }
    }
}

juce::AudioProcessorEditor* InstrudioProcessor::createEditor()
{
    return new InstrudioEditor(*this);
}

void InstrudioProcessor::getStateInformation(juce::MemoryBlock& destData)
{
    // Save current instrument selection
    juce::ValueTree state("InstrudioState");
    state.setProperty("instrument", currentInstrument, nullptr);
    juce::MemoryOutputStream stream(destData, false);
    state.writeToStream(stream);
}

void InstrudioProcessor::setStateInformation(const void* data, int sizeInBytes)
{
    auto state = juce::ValueTree::readFromData(data, (size_t)sizeInBytes);
    if (state.isValid())
    {
        auto inst = state.getProperty("instrument", "violin").toString();
        setInstrument(inst);
    }
}

void InstrudioProcessor::setInstrument(const juce::String& instrumentId)
{
    currentInstrument = instrumentId;

    // Map instrument IDs to page filenames
    struct InstrumentPage { const char* id; const char* file; };
    static const InstrumentPage pages[] = {
        {"violin", "violin.html"}, {"piano", "piano.html"},
        {"harp", "harp.html"}, {"bongo", "bongo.html"},
        {"guitar", "guitar.html"}, {"saxophone", "saxophone.html"},
        {"accordion", "accordion.html"}, {"harmonica", "harmonica.html"},
        {"bagpipes", "bagpipes.html"}, {"triangle", "triangle.html"},
    };

    for (auto& p : pages)
    {
        if (instrumentId == p.id)
        {
            currentURL = BASE_URL + p.file;
            return;
        }
    }
    currentURL = BASE_URL + "violin.html";
}

void InstrudioProcessor::webViewNoteOn(int note, float velocity)
{
    const juce::ScopedLock sl(midiLock);
    auto msg = juce::MidiMessage::noteOn(1, note, velocity);
    pendingWebMidi.addEvent(msg, 0);
}

void InstrudioProcessor::webViewNoteOff(int note)
{
    const juce::ScopedLock sl(midiLock);
    auto msg = juce::MidiMessage::noteOff(1, note);
    pendingWebMidi.addEvent(msg, 0);
}

// This creates new instances of the plugin
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new InstrudioProcessor();
}
